[package]
name = "bls_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "bls_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.30.0"
bls = { git = "https://github.com/sigp/lighthouse", package = "bls" }
