[package]
name = "ssz_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ssz_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
ethereum_ssz_derive = "0.5.0"
ethereum_ssz = "0.5.0"
ssz_types = "0.5.4"
tree_hash = "0.5.2"
tree_hash_derive = "0.5.2"
